version: "3"
services:
    MySQL_DB:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DBNAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PWD}

    Alphitter:
        build: .
        image: weitungstyle/alphitter:latest
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        env_file:
            - ./.env
        depends_on:
            - MySQL_DB
